### ISSUE TITLE
Add a table for the bibliography

### ISSUE THREAD

**Issue by hamishgibbs** [hamishgibbs/lit_review_graph#3]
Would be nice to have a table of the papers in the bibliography (could be collapsible?) at the beginning so you can check the stats of the seed papers quickly.

**Comment by hamishgibbs** [comment]
If collapsible, default to collapsed

**Comment by lousieg** [comment]
That would be very helpful! please do this :)

**Comment by hamishgibbs** [comment]
Closed by #6

**Comment by hamishgibbs** [comment]
FYI @lousieg – you will need to pull the latest changes into your local repository (`git pull`)

**Comment by lousieg** [comment]
noted! thanks a lot for reminding me
