### ISSUE TITLE
Add a table for bibliography (reopening #3)

### ISSUE THREAD

**Issue by lousieg** [hamishgibbs/lit_review_graph#7]
Issue #3 was closed, but the table created lists all connected references rather than the papers in the original text file bibliography, as I believe was the original intention.

**Comment by hamishgibbs** [comment]
Lol - a small omission: https://github.com/hamishgibbs/lit_review_graph/pull/8/commits/588b6f0f47ac181ee3d2f7e18ccee60a32f2a98d
